# Generated by Django 5.0.7 on 2024-07-24 16:35

import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("title", models.CharField(max_length=16)),
                (
                    "daily_goal",
                    models.PositiveIntegerField(default=0, help_text="일일 목표치"),
                ),
                (
                    "total_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="전체 달성률",
                        max_digits=7,
                    ),
                ),
                ("start_at", models.DateField()),
                ("end_at", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
                "db_table": "board",
            },
        ),
        migrations.CreateModel(
            name="DailyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "goal",
                    models.PositiveIntegerField(default=0, help_text="일일 목표치"),
                ),
                (
                    "achievement",
                    models.PositiveIntegerField(default=0, help_text="실제 달성 횟수"),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="일일 달성률",
                        max_digits=7,
                    ),
                ),
                ("target_date", models.DateField()),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="checker_board.board",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistics",
                "verbose_name_plural": "Statistics",
                "db_table": "statistics",
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("title", models.CharField(max_length=16)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="checker_board.board",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "db_table": "mission",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAction",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("title", models.CharField(max_length=16)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            (0, "Once"),
                            (1, "Daily"),
                            (7, "Weekly"),
                            (30, "Monthly"),
                            (365, "Yearly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("goal_unit", models.PositiveIntegerField(help_text="목표치")),
                ("action_unit", models.PositiveIntegerField(help_text="수행 단위")),
                (
                    "current_unit",
                    models.PositiveIntegerField(default=0, help_text="실제 수행치"),
                ),
                ("achievement", models.PositiveIntegerField(default=0)),
                ("unit_name", models.CharField(max_length=8)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="checker_board.board",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="checker_board.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Action",
                "verbose_name_plural": "historical Actions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("title", models.CharField(max_length=16)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            (0, "Once"),
                            (1, "Daily"),
                            (7, "Weekly"),
                            (30, "Monthly"),
                            (365, "Yearly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("goal_unit", models.PositiveIntegerField(help_text="목표치")),
                ("action_unit", models.PositiveIntegerField(help_text="수행 단위")),
                (
                    "current_unit",
                    models.PositiveIntegerField(default=0, help_text="실제 수행치"),
                ),
                ("achievement", models.PositiveIntegerField(default=0)),
                ("unit_name", models.CharField(max_length=8)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="checker_board.board",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="checker_board.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
                "db_table": "action",
                "unique_together": {("board", "position")},
            },
        ),
    ]
