# Generated by Django 5.0.7 on 2024-07-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker_board", "0004_alter_action_deleted_alter_board_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="achievement",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="action",
            name="current_unit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="board",
            name="achievement",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
