# Generated by Django 5.0.7 on 2024-07-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker_board", "0005_action_achievement_action_current_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="checker_board.board",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="action",
            unique_together={("board", "position")},
        ),
    ]
