version: '3.4'

volumes:
  db_data: { }
  static_data: { }
  redis_data: { }

services:
  nginx:
    container_name: nginx
    image: nginx:stable
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/make-me-better-mandalart-be/static/
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./apps/
        target: /make-me-better-mandalart-be/apps/
      - static_data:/make-me-better-mandalart-be/static
      - db_data:/make-me-better-mandalart-be/db_data
    ports:
      - '8000:8000'
    command:
      - bash
      - -c
      - |
        pip install requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        gunicorn --bind 0:8000 config.wsgi:application

    tty: true
