# Generated by Django 5.0.7 on 2024-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker_board", "0003_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="deleted",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="deleted",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="deleted",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
